### ISSUE TITLE
convert-triton-cpu-to-llvm pass failing on vector_add example. 

### ISSUE THREAD

**Issue by kapilsh** [pytorch-labs/triton-cpu#5]
Hey folks, Thanks for amazing work on the triton-cpu backend. I was just testing it out but got an error during kernel compilation for one of the tutorial examples. Just filing an issue in case this wasn't a known issue. 

Repro: `MLIR_ENABLE_DUMP=1 TRITON_CPU_BACKEND=1 python3 python/tutorials/01-vector-add.py`

```
error: failed to legalize operation 'tt.get_program_id' that was explicitly marked illegal
```

MLIR dump: https://gist.github.com/kapilsh/f7656283299899abfce4f020092a06cf

Stack trace.
```
Traceback (most recent call last):
  File "/home/ksharma/dev/git/triton-cpu/python/tutorials/01-vector-add.py", line 87, in <module>
    output_triton = add(x, y)
                    ^^^^^^^^^
  File "/home/ksharma/dev/git/triton-cpu/python/tutorials/01-vector-add.py", line 73, in add
    add_kernel[grid](x, y, output, n_elements, BLOCK_SIZE=1024)
  File "/home/ksharma/dev/git/triton-cpu/python/triton/runtime/jit.py", line 209, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksharma/dev/git/triton-cpu/python/triton/runtime/jit.py", line 526, in run
    kernel = self.compile(
             ^^^^^^^^^^^^^
  File "/home/ksharma/dev/git/triton-cpu/python/triton/compiler/compiler.py", line 278, in compile
    next_module = compile_ir(module, metadata)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksharma/dev/git/triton-cpu/python/triton/backends/cpu/compiler.py", line 151, in <lambda>
    stages["llir"] = lambda src, metadata: self.make_llir(src, metadata, options)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksharma/dev/git/triton-cpu/python/triton/backends/cpu/compiler.py", line 112, in make_llir
    pm.run(mod)
RuntimeError: PassManager::run failed
```

**Comment by minjang** [comment]
The current main branch is healthy. I also checked with your repro and it works good. The resulting IRs are not correct. Can you try it one more time with a clean installation?

**Comment by kapilsh** [comment]
Ohh I realized just now that this is older. The most up to date code is on https://github.com/triton-lang/triton-cpu/. 

may be we should redirect to https://github.com/triton-lang/triton-cpu/ for updated code?
